### ISSUE TITLE
No Fall Damage

### ISSUE THREAD

**Issue by WongIong** [MrMicky-FR/InfiniteJump#14] opened 2022-06-04 00:38 UTC
When player triggered their jump, the fall damage will be counted.
But if they didn't trigger it, they won't get damage.

I think this is because the flight mode is always on when they were available to jump. So that minecraft will not calculate their fall damage.
Maybe you will have to calculate it inside the plugin and then give the damage to player.

**Comment by MrMicky-FR** [comment] 2022-07-17 16:19
Duplicate of #7

**Closed as not planned by MrMicky-FR** 2022-07-17 16:19 UTC
